ARG BASE_IMAGE=ghcr.io/dmitriy-py/ros2-cuda-base:x86_64
FROM ${BASE_IMAGE}

ARG REPO_URL
ARG REPO_BRANCH="ROS2"
ARG PACKAGE_NAME="FAST_LIO"
ARG CUDA_ARCH="8.7"

ENV CUDA_ARCH=${CUDA_ARCH}
ENV CMAKE_CUDA_ARCHITECTURES=${CUDA_ARCH}

# 1. Установка Livox-SDK2 в систему
RUN cd /tmp && \
    git clone https://github.com/Livox-SDK/Livox-SDK2.git && \
    cd Livox-SDK2 && mkdir build && cd build && \
    cmake .. && make -j$(nproc) && make install && \
    ldconfig && \
    rm -rf /tmp/Livox-SDK2

WORKDIR /ros2_ws/src

# 2. Клонирование FAST_LIO (ветка ROS2)
RUN git clone --recursive -b ROS2 https://github.com/hku-mars/FAST_LIO.git || \
    git clone --recursive https://github.com/hku-mars/FAST_LIO.git

# 3. Клонирование и подготовка livox_ros_driver2
RUN git clone https://github.com/Livox-SDK/livox_ros_driver2.git && \
    cd livox_ros_driver2 && \
    cp package_ROS2.xml package.xml

WORKDIR /ros2_ws

# 4. Установка всех системных и ROS2 зависимостей
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    apt-get update && \
    rosdep install --from-paths src --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*

# 5. Последовательная сборка: сначала driver2 (создает custom_msg), затем весь workspace
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --symlink-install --packages-select livox_ros_driver2 \
    --cmake-args -DCMAKE_BUILD_TYPE=Release -DROS_EDITION=ROS2 -DCMAKE_CUDA_ARCHITECTURES="${CUDA_ARCH}" && \
    . /ros2_ws/install/setup.sh && \
    colcon build --symlink-install \
    --cmake-args -DCMAKE_BUILD_TYPE=Release -DROS_EDITION=ROS2 -DCMAKE_CUDA_ARCHITECTURES="${CUDA_ARCH}"

# Настройка окружения
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
    echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc

ENTRYPOINT ["/bin/bash", "-c", "source /ros2_ws/install/setup.bash && exec \"$@\"", "--"]
CMD ["bash"]
