name: 01 - Build and Push Base Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-base-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/base/Dockerfile.x86_64
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/ros2-cuda-base:x86_64

  build-base-orin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64'
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/base/Dockerfile.orin
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/ros2-cuda-base:orin
